.data
next:
        .space  32
dir:
        .word   0
head:
        .word   0
tail:
        .word   0
N:
        .word   0
a:
        .word   0
b:
        .word   0
snakex:
        .space  4096
snakey:
        .space  4096
foodx:
        .word   0
foody:
        .word   0
score:
        .word   0
foodstatus:
        .word   0
vis:
        .space  64
.text
main:
        addi    sp,sp,-48
        addi    s0,sp,48
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        sw      zero,0(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        li      a4,1
        sw      a4,4(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        li      a4,1
        sw      a4,8(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        sw      zero,12(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        li      a4,-1
        sw      a4,16(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        sw      zero,20(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        sw      zero,24(a5)
        lui     a5,%hi(next)
        addi    a5,a5,%lo(next)
        li      a4,-1
        sw      a4,28(a5)
        lui     a5,%hi(a)
        li      a4,17
        addi    a3,a5,%lo(a)
        sw      a4,(a3)
        lui     a5,%hi(b)
        li      a4,13
        addi    a3,a5,%lo(b)
        sw      a4,(a3)
        lui     a5,%hi(foodx)
        li      a4,10
        addi    a3,a5,%lo(foodx)
        sw      a4,(a3)
        lui     a5,%hi(foody)
        li      a4,5
        addi    a3,a5,%lo(foody)
        sw      a4,(a3)
        lui     a5,%hi(foodstatus)
        li      a4,0
        addi    a3,a5,%lo(foodstatus)
        sw      a4,(a3)
        lui     a5,%hi(snakex)
        addi    a5,a5,%lo(snakex)
        li      a4,16
        sw      a4,0(a5)
        lui     a5,%hi(snakey)
        addi    a5,a5,%lo(snakey)
        li      a4,16
        sw      a4,0(a5)
        lui     a5,%hi(vis)
        addi    a5,a5,%lo(vis)
        li      a4,65536
        sw      a4,64(a5)
        lui     a5,%hi(N)
        li      a4,1024
        addi    a3,a5,%lo(N)
        sw      a4,(a3)
.L11:
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        addi    a5,a5,1
        mv      a4,a5
        lui     a5,%hi(N)
        lw      a5,%lo(N)(a5)
        remu    a5,a4,a5
        sw      a5,-28(s0)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(dir)
        lw      a5,%lo(dir)(a5)
        lui     a3,%hi(next)
        addi    a3,a3,%lo(next)
        slli    a5,a5,3
        add     a5,a3,a5
        lw      a5,0(a5)
        add     a4,a4,a5
        lui     a5,%hi(snakex)
        addi    a3,a5,%lo(snakex)
        lw      a5,-28(s0)
        slli    a5,a5,2
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(dir)
        lw      a5,%lo(dir)(a5)
        lui     a3,%hi(next)
        addi    a3,a3,%lo(next)
        slli    a5,a5,3
        add     a5,a3,a5
        lw      a5,4(a5)
        add     a4,a4,a5
        lui     a5,%hi(snakey)
        addi    a3,a5,%lo(snakey)
        lw      a5,-28(s0)
        slli    a5,a5,2
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a4,-28(s0)
        addi    a3,a5,%lo(head)
        sw      a4,(a3)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        blt     a5,zero,.L3
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        li      a5,31
        bgt     a4,a5,.L3
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        blt     a5,zero,.L3
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        li      a5,31
        bgt     a4,a5,.L3
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(foodx)
        lw      a5,%lo(foodx)(a5)
        bne     a4,a5,.L4
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(foody)
        lw      a5,%lo(foody)(a5)
        bne     a4,a5,.L4
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        lui     a4,%hi(vis)
        addi    a4,a4,%lo(vis)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a3,%hi(snakey)
        addi    a3,a3,%lo(snakey)
        slli    a5,a5,2
        add     a5,a3,a5
        lw      a5,0(a5)
        srl     a5,a4,a5
        andi    a5,a5,1
        sw      a5,-32(s0)
        lw      a5,-32(s0)
        bne     a5,zero,.L13
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        lui     a4,%hi(vis)
        addi    a4,a4,%lo(vis)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a3,0(a5)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        li      a4,1
        sll     a4,a4,a5
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a2,%hi(snakex)
        addi    a2,a2,%lo(snakex)
        slli    a5,a5,2
        add     a5,a2,a5
        lw      a5,0(a5)
        or      a4,a3,a4
        lui     a3,%hi(vis)
        addi    a3,a3,%lo(vis)
        slli    a5,a5,2
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(foodx)
        lw      a5,%lo(foodx)(a5)
        mv      a4,a5
        lui     a5,%hi(a)
        lw      a5,%lo(a)(a5)
        mul     a4,a4,a5
        lui     a5,%hi(b)
        lw      a5,%lo(b)(a5)
        add     a4,a4,a5
        lui     a5,%hi(N)
        lw      a5,%lo(N)(a5)
        remu    a5,a4,a5
        mv      a4,a5
        lui     a5,%hi(foodx)
        addi    a3,a5,%lo(foodx)
        sw      a4,(a3)
        lui     a5,%hi(foody)
        lw      a5,%lo(foody)(a5)
        mv      a4,a5
        lui     a5,%hi(a)
        lw      a5,%lo(a)(a5)
        mul     a4,a4,a5
        lui     a5,%hi(b)
        lw      a5,%lo(b)(a5)
        add     a4,a4,a5
        lui     a5,%hi(N)
        lw      a5,%lo(N)(a5)
        remu    a5,a4,a5
        mv      a4,a5
        lui     a5,%hi(foody)
        addi    a3,a5,%lo(foody)
        sw      a4,(a3)
        lui     a5,%hi(score)
        lw      a5,%lo(score)(a5)
        addi    a4,a5,1
        lui     a5,%hi(score)
        addi    a3,a5,%lo(score)
        sw      a4,(a3)
        lui     a5,%hi(foodstatus)
        li      a4,1
        addi    a3,a5,%lo(foodstatus)
        sw      a4,(a3)
        j       .L6
.L4:
        lui     a5,%hi(tail)
        lw      a5,%lo(tail)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        lui     a4,%hi(vis)
        addi    a4,a4,%lo(vis)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a3,0(a5)
        lui     a5,%hi(tail)
        lw      a5,%lo(tail)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        li      a4,1
        sll     a4,a4,a5
        lui     a5,%hi(tail)
        lw      a5,%lo(tail)(a5)
        lui     a2,%hi(snakex)
        addi    a2,a2,%lo(snakex)
        slli    a5,a5,2
        add     a5,a2,a5
        lw      a5,0(a5)
        xor     a4,a3,a4
        lui     a3,%hi(vis)
        addi    a3,a3,%lo(vis)
        slli    a5,a5,2
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(tail)
        lw      a5,%lo(tail)(a5)
        addi    a5,a5,1
        mv      a4,a5
        lui     a5,%hi(N)
        lw      a5,%lo(N)(a5)
        remu    a5,a4,a5
        mv      a4,a5
        lui     a5,%hi(tail)
        addi    a3,a5,%lo(tail)
        sw      a4,(a3)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        lui     a4,%hi(vis)
        addi    a4,a4,%lo(vis)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a4,0(a5)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a3,%hi(snakey)
        addi    a3,a3,%lo(snakey)
        slli    a5,a5,2
        add     a5,a3,a5
        lw      a5,0(a5)
        srl     a5,a4,a5
        andi    a5,a5,1
        sw      a5,-36(s0)
        lw      a5,-36(s0)
        bne     a5,zero,.L14
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakex)
        addi    a4,a4,%lo(snakex)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        lui     a4,%hi(vis)
        addi    a4,a4,%lo(vis)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a3,0(a5)
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a4,%hi(snakey)
        addi    a4,a4,%lo(snakey)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        li      a4,1
        sll     a4,a4,a5
        lui     a5,%hi(head)
        lw      a5,%lo(head)(a5)
        lui     a2,%hi(snakex)
        addi    a2,a2,%lo(snakex)
        slli    a5,a5,2
        add     a5,a2,a5
        lw      a5,0(a5)
        or      a4,a3,a4
        lui     a3,%hi(vis)
        addi    a3,a3,%lo(vis)
        slli    a5,a5,2
        add     a5,a3,a5
        sw      a4,0(a5)
        lui     a5,%hi(foodstatus)
        lw      a5,%lo(foodstatus)(a5)
        xori    a4,a5,1
        lui     a5,%hi(foodstatus)
        addi    a3,a5,%lo(foodstatus)
        sw      a4,(a3)
.L6:
        sw      zero,-20(s0)
        j       .L8
.L10:
        lui     a5,%hi(vis)
        addi    a4,a5,%lo(vis)
        lw      a5,-20(s0)
        slli    a5,a5,2
        add     a5,a4,a5
        lw      a5,0(a5)
        sw      a5,-24(s0)
        lui     a5,%hi(foodx)
        lw      a5,%lo(foodx)(a5)
        lw      a4,-20(s0)
        bne     a4,a5,.L9
        lui     a5,%hi(foody)
        lw      a5,%lo(foody)(a5)
        lw      a4,-24(s0)
        srl     a5,a4,a5
        andi    a5,a5,1
        lui     a4,%hi(foodstatus)
        lw      a4,%lo(foodstatus)(a4)
        beq     a5,a4,.L9
        lui     a5,%hi(foody)
        lw      a5,%lo(foody)(a5)
        li      a4,1
        sll     a5,a4,a5
        lw      a4,-24(s0)
        xor     a5,a4,a5
        sw      a5,-24(s0)
.L9:
        lw      a0,-24(s0)
        addi    a7,zero,34
        ecall
        lw      a5,-20(s0)
        addi    a5,a5,1
        sw      a5,-20(s0)
.L8:
        lw      a4,-20(s0)
        li      a5,31
        ble     a4,a5,.L10
        j       .L11
.L13:
        nop
        j       .L3
.L14:
        nop
.L3:
        lui     a5,%hi(dir)
        li      a4,1919810
        addi    a3,a5,%lo(dir)
        sw      a4,(a3)
        li      a5,0
        mv      a0,a5
        addi    sp,sp,48
        addi    a7,zero,10    
        ecall
interrupt:
        sw      a3,0(sp)
        addi    sp,sp,4
        sw      a4,0(sp)
        addi    sp,sp,4
        sw      a5,0(sp)
        addi    sp,sp,4
        lui     a5,%hi(dir)
        li      a4,114514
        addi    a3,a5,%lo(dir)
        sw      a4,(a3)
        addi    sp,sp,-4
        lw      a3,0(sp)
        addi    sp,sp,-4
        lw      a4,0(sp)
        addi    sp,sp,-4
        lw      a5,0(sp)
        uret